// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hfjomkwatyvwmcyugzfu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhmam9ta3dhdHl2d21jeXVnemZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU3ODU3ODAsImV4cCI6MjA1MTM2MTc4MH0.IFphhbxGLN8OD2HZJtf5TR8_Q3HzwuqjwjW7bykCrrE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);